"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "chave-apenas-para-desenvolvimento",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
).split(",")


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "apps.animais",
    "apps.ocorrencias",
    "apps.avistamentos",
    "apps.usuarios",
    "apps.comunicacoes",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "pet_encontrado"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Bahia"

USE_I18N = True
USE_TZ = True


STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "password_reset_request": "5/hour",
        "password_reset_confirm": "10/hour",
    },
}


FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173",
).rstrip("/")

def obter_configuracao_email(variaveis=None):
    variaveis = os.environ if variaveis is None else variaveis
    email_host = variaveis.get("EMAIL_HOST", "").strip()
    usa_ssl = variaveis.get("EMAIL_USE_SSL", "False").lower() == "true"
    usa_tls = variaveis.get("EMAIL_USE_TLS", "True").lower() == "true"

    return {
        "EMAIL_BACKEND": (
            "django.core.mail.backends.smtp.EmailBackend"
            if email_host
            else "django.core.mail.backends.console.EmailBackend"
        ),
        "EMAIL_HOST": email_host,
        "EMAIL_PORT": int(variaveis.get("EMAIL_PORT", "587")),
        "EMAIL_HOST_USER": variaveis.get("EMAIL_HOST_USER", ""),
        "EMAIL_HOST_PASSWORD": variaveis.get("EMAIL_HOST_PASSWORD", ""),
        "EMAIL_USE_TLS": usa_tls and not usa_ssl,
        "EMAIL_USE_SSL": usa_ssl,
        "DEFAULT_FROM_EMAIL": variaveis.get(
            "DEFAULT_FROM_EMAIL",
            "nao-responda@mypetfound.local",
        ),
    }


_configuracao_email = obter_configuracao_email()
EMAIL_BACKEND = _configuracao_email["EMAIL_BACKEND"]
EMAIL_HOST = _configuracao_email["EMAIL_HOST"]
EMAIL_PORT = _configuracao_email["EMAIL_PORT"]
EMAIL_HOST_USER = _configuracao_email["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = _configuracao_email["EMAIL_HOST_PASSWORD"]
EMAIL_USE_TLS = _configuracao_email["EMAIL_USE_TLS"]
EMAIL_USE_SSL = _configuracao_email["EMAIL_USE_SSL"]
DEFAULT_FROM_EMAIL = _configuracao_email["DEFAULT_FROM_EMAIL"]
