# Generated by Django 5.2.17 on 2026-09-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESAPARECIMENTO', 'Desaparecimento'), ('REENCONTRO', 'Reencontro')], default='DESAPARECIMENTO', max_length=20, verbose_name='Tipo de ocorrência')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=10, verbose_name='Status da ocorrência')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora da ocorrência')),
                ('localidade', models.CharField(help_text='Ex.: Bairro Ceraíma, Guanambi-BA', max_length=255, verbose_name='Último local visto')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, help_text='Ex.: Fugiu quando o portão ficou aberto.', verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='animais.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_hora'],
            },
        ),
    ]
