# Generated by Django 5.2.17 on 2026-09-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avistamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avistamentos/%Y/%m/', verbose_name='Foto do avistamento')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora do avistamento')),
                ('localidade', models.CharField(help_text='Ex.: Bairro Beija-Flor, Guanambi-BA', max_length=255, verbose_name='Local do avistamento')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, help_text='Ex.: Estava perto da praça, parecia assustado e estava sem coleira.', verbose_name='Descrição')),
                ('nome_contato', models.CharField(blank=True, max_length=100, verbose_name='Nome de quem avistou')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, verbose_name='Telefone de contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ocorrencia', models.ForeignKey(limit_choices_to={'status': 'ATIVA', 'tipo': 'DESAPARECIMENTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='avistamentos', to='ocorrencias.ocorrencia', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name': 'Avistamento',
                'verbose_name_plural': 'Avistamentos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
