# Generated by Django 5.2.17 on 2026-10-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0003_avisoidentificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('localizacao_texto', models.CharField(blank=True, max_length=255, verbose_name='Local informado')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_contato', to='animais.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-criada_em'],
            },
        ),
    ]
