# Generated by Django 5.2.17 on 2026-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('especie', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Espécie')),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('porte', models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Porte')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor predominante')),
                ('descricao', models.TextField(blank=True, help_text='Ex.: mancha branca no peito, usa coleira azul, manca da pata traseira.', verbose_name='Características e observações')),
                ('status', models.CharField(choices=[('CADASTRADO', 'Cadastrado'), ('PERDIDO', 'Perdido'), ('REENCONTRADO', 'Reencontrado')], default='CADASTRADO', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
