# Generated by Django 5.2.17 on 2026-10-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoIdentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(blank=True, max_length=100, verbose_name='Nome de quem encontrou')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone ou WhatsApp')),
                ('localidade', models.CharField(max_length=200, verbose_name='Local onde o animal está ou foi visto')),
                ('mensagem', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_identificacao', to='animais.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Aviso de identificação',
                'verbose_name_plural': 'Avisos de identificação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
