# Generated by Django 5.2.17 on 2026-10-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_avisoidentificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvisoIdentificacao',
        ),
    ]
