# Generated by Django 5.2.17 on 2026-10-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_delete_avisoidentificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais/%Y/%m/', verbose_name='Foto principal'),
        ),
    ]
