# Generated by Django 5.2.17 on 2026-10-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_animal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea'), ('', 'Não informado')], default='', max_length=1, verbose_name='Sexo'),
        ),
    ]
