# Generated by Django 5.2.17 on 2026-10-09 02:32

from django.db import migrations


def preencher_sexo_padrao(apps, schema_editor):
    Animal = apps.get_model('animais', 'Animal')
    Animal.objects.filter(sexo='').update(sexo='M')


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_animal_sexo'),
    ]

    operations = [
        migrations.RunPython(preencher_sexo_padrao, migrations.RunPython.noop),
    ]
