# Generated by Django 5.2.17 on 2026-10-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_preencher_sexo_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo'),
        ),
    ]
